apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-web-application
  template:
    metadata:
      labels:
        app: maven-web-application
    spec:
      containers:
        - name: maven-web-application
          image: your-docker-username/maven-web-application:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-application-service
spec:
  selector:
    app: maven-web-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
